services:
  postgres:
    container_name: postgres-sql
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: basicdatabase
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - spring-network
    restart: unless-stopped

  pgadmin-docker:
    image: dpage/pgadmin4
    container_name: pgadmin-servicesql
    environment:
      PGADMIN_DEFAULT_EMAIL: usuario@pokemail.net
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - 5050:80
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - spring-network

  mail-dev:
    container_name: mail-dev-demo
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  spring-network:
    driver: bridge

volumes:
  postgres:
    driver: local